language: ruby

rvm:
  - 2.3

services:
  - docker

cache: bundler

jobs:
  include:
    - stage: "Tests"
      before_install:
        - sudo apt-get update > /dev/null && sudo apt-get install -y git build-essential libgeos-dev zlib1g-dev zlib1g > /dev/null
        - docker create -it --name or_tools ${REGISTRY:-registry.mapotempo.com/}mapotempo/ortools:${ORTOOLS_VERSION:-v7.0}
        - docker cp or_tools:/srv/or-tools $(dirname "${TRAVIS_BUILD_DIR}")
        - ls -lh $(dirname "${TRAVIS_BUILD_DIR}")/or-tools
        - docker create -it --name vroom ${REGISTRY:-registry.mapotempo.com/}mapotempo/vroom:${VROOM_VERSION:-v1.2.0}
        - docker cp vroom:/srv/vroom $(dirname "${TRAVIS_BUILD_DIR}")
        - ls -lh $(dirname "${TRAVIS_BUILD_DIR}")/vroom
        - sudo docker cp vroom:/usr/lib/x86_64-linux-gnu /usr/lib
        - docker create -it --name optimizer_ortools ${REGISTRY:-registry.mapotempo.com/}mapotempo-${BRANCH:-ce}/optimizer-ortools:${OPTIMIZER_ORTOOLS_VERSION:-latest}
        - docker cp optimizer_ortools:/srv/optimizer-ortools $(dirname "${TRAVIS_BUILD_DIR}")
        - ls -lh $(dirname "${TRAVIS_BUILD_DIR}")/optimizer-ortools
        - ls -lh ${TRAVIS_BUILD_DIR}
      env: TEST_SUITE='basis'
      script: bash ci-utils/tests.sh ${TEST_SUITE}
    - env: TEST_SUITE='dicho'
      script: travis_wait 60 bash ci-utils/tests.sh ${TEST_SUITE}
    - env: TEST_SUITE='scheduling'
      script: bash ci-utils/tests.sh ${TEST_SUITE}
    - env: TEST_SUITE='real_scheduling'
      script: travis_wait 60 bash ci-utils/tests.sh ${TEST_SUITE}
    - env: TEST_SUITE='real_scheduling_solver'
      script: travis_wait 60 bash ci-utils/tests.sh ${TEST_SUITE}
    - env: TEST_SUITE='split_clustering'
      script: bash ci-utils/tests.sh ${TEST_SUITE}
    - env: TEST_SUITE='real'
      script: bash ci-utils/tests.sh ${TEST_SUITE}
    # - script: bash ci-utils/tests.sh real_dicho -> should be runned locally because test are too big to dump matrices
    - stage: "Dockerize and tests (using basis suite)"
      install: skip
      script: bash ci-utils/dockerize.sh