services:
  - docker

jobs:
  include:
    - stage: "Tests"
      install: skip
      before_install:
        - export REGISTRY=registry.mapotempo.com/
        - docker build --build-arg VROOM_VERSION=${VROOM_VERSION:-v1.2.0} --build-arg OPTIMIZER_ORTOOLS_VERSION=${OPTIMIZER_ORTOOLS_VERSION:-v0.1} -f docker/Dockerfile -t registry.test.com/mapotempo/optimizer-api:latest .
        - docker swarm init
        - mkdir -p ./redis
        - docker stack deploy -c ./docker/docker-compose.yml optimizer
      env: TEST_SUITE='basis'
      script: bash ci-utils/tests.sh ${TEST_SUITE}
    - env: TEST_SUITE='dicho'
      script: travis_wait 60 bash ci-utils/tests.sh ${TEST_SUITE}
    - env: TEST_SUITE='scheduling'
      script: bash ci-utils/tests.sh ${TEST_SUITE}
    - env: TEST_SUITE='real_scheduling'
      script: travis_wait 60 bash ci-utils/tests.sh ${TEST_SUITE}
    - env: TEST_SUITE='real_scheduling_solver'
      script: travis_wait 60 bash ci-utils/tests.sh ${TEST_SUITE}
    - env: TEST_SUITE='split_clustering'
      script: bash ci-utils/tests.sh ${TEST_SUITE}
    - env: TEST_SUITE='real'
      script: bash ci-utils/tests.sh ${TEST_SUITE}
    - stage: deploy
      name: "Deploy"
      install: skip
      skip_cleanup: true
      if: tag ~= /^v.*/
      script:
        - echo "> pushing tag ${TRAVIS_TAG}"
        - IMAGE_NAME=${REGISTRY}/mapotempo-ce/optimizer-api:${TRAVIS_TAG}
        - docker tag registry.test.com/mapotempo/optimizer-api:latest ${IMAGE_NAME}
        - docker push ${IMAGE_NAME}
